services:
  vcardonabp.httpapi.host:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Default=Server=db;User=sa;Password=Caube_2k2@;Database=VCardOnAbp;Trusted_Connection=false;TrustServerCertificate=true
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Caube_2k2
      - AuthServer__Authority=https://api.vccus.net
      - AuthServer__RequireHttpsMetadata=true
      - AuthServer__SwaggerClientId=VCCUS
      - ThirdParty__Vcc51__Url=https://www.51vcc.com
      - ThirdParty__Vcc51__Cookie=3qqjsa23a5a4azjo4ff4ymsz
      - Redis__Configuration=redis:6379,password=Wu9xd87Qj74LBW2
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${USERPROFILE}/.aspnet/https:/https/
    depends_on:
      - db  # Ensures that the app starts after the database is up
      - redis
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Caube_2k2@
    ports:
      - "1434:1433"  # Exposes SQL Server on port 1433
    volumes:
      - db_data:/var/opt/mssql  # Persist database data between container restarts
    networks:
      - default
  redis:
    image: redis:7.0-alpine # Redis phiên bản nhẹ với Alpine Linux
    command: redis-server --requirepass Wu9xd87Qj74LBW2 --appendonly yes # Bật chế độ lưu trữ dữ liệu trên disk
    ports:
      - "6379:6379" # Cổng mặc định của Redis
    volumes:
      - redis_data:/data # Lưu trữ dữ liệu Redis
    networks:
      - default
volumes:
  db_data: # This defines the volume for the SQL Server data persistence.
  redis_data: # This defines the volume for the Redis data persistence.